### ISSUE TITLE
Memory is consumed and not released with every login

### ISSUE THREAD

**Issue by GeoffCraigVRU** [auth0/auth0-aspnetcore-authentication#86]
### Describe the problem
When using auth0-aspnetcore-authentication with a Blazor application, every new login uses 40MB of memory and is never released.  The application eventually becomes unresponsive.

If Auth0.AspNetCore.Authentication is removed and Microsoft.AspNetCore.Authentication.OpenIdConnect is used there are no memory issues.

This was reported before, however this is a blocking issue and this package cannot be used.

### What was the expected behavior?

Memory should be released.

### Reproduction
Build a .net 6.0 Blazor app using Auth0.AspNetCore.Authentication.  Set the options to include .WithAccessToken.  Login in and out a few times and look at the memory utilization.

### Environment
.Net 6.0
auth0-aspnetcore-authentication 1.0.3
DockerDefaultTargetOS: Docker

**Comment by frederikprijck** [comment]
Thanks for raising this, [as mentioned](https://github.com/auth0/auth0-aspnetcore-authentication/issues/80#issuecomment-1248582998) in https://github.com/auth0/auth0-aspnetcore-authentication/issues/80, this appears to be a leak that originated from inside the Microsoft.AspNetCore.Authentication.OpenIdConnect package.

This should be reproducible without our SDK.

Keeping this open, as I want to give this another look as to if there is anything we can do about this from our side or not and will open an issue with Microsoft if needed.

**Comment by brian-agencyroot** [comment]
Any updates on this? We're in the process of deploying multiple Blazor Server apps to our Kubernetes cluster and we are experiencing the same behavior. Have you been able to find an issue on the Auth0 side or has a formal issue been raised with Microsoft that I can follow?

**Comment by frederikprijck** [comment]
Thanks, sorry for not getting back to this.

Can you verify what version of Microsoft.IdentityModel.Protocols.OpenIdConnect and `Microsoft.IdentityModel.Tokens` you are using?

I have been able to reproduce the behavior with any version below `6.12.0`. As of 6.12.0, I can not reproduce the behavior. It's mentioned to be fixed in the release notes: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.12.0

It appears that when you install `6.0.11` of `Microsoft.AspNetCore.Authentication.OpenIdConnect`, which is the latest version for .NET 6, it automatically installs `Microsoft.IdentityModel.Protocols.OpenIdConnect` 6.10.0, which contains the bug.

We could solve this in our SDK by pinning the version, but I prefer to not pin to any versions. This leak also exists when using `Microsoft.AspNetCore.Authentication.OpenIdConnect` directly, see https://github.com/frederikprijck/oidcleak.

For now, please ensure you install a version of `Microsoft.IdentityModel.Protocols.OpenIdConnect` thats greater than 6.12.0.
Ideally installing `6.0.11` of `Microsoft.AspNetCore.Authentication.OpenIdConnect` should not install `6.10.0` of `Microsoft.IdentityModel.Protocols.OpenIdConnect`.

**Comment by brian-agencyroot** [comment]
Thanks for the quick reply! I've updated the implicitly referenced packages to their latest versions (6.25.1) and redeployed the app a little while ago. CPU and Memory stats are lower than they have ever been before, so I'm pretty confident, so far anyway, that this may be the fix we needed. Thanks again!

**Comment by frederikprijck** [comment]
Thanks for the feedback. I will leave this open for now until we have a fix, either by bumping versions at Microsoft side, or our side if realy needed.
